# Use `gdpack add` to import addon dependencies into your project.
# 
# For example:
#    gdpack add https://github.com/bitwes/Gut --tag v9.1.1 -d

[project.export_files]
  # A list of glob expressions which, when any match are matched, cause an addon
  # file to *not* be installed into a Godot project. This option is particularly
  # useful for omitting files and folders from an addon with a root 'plugin.cfg'.
  # Note that hidden files and folders and the 'gdpack.toml' manifest are excluded
  # by default.
  exclude = ["bin", "icon.svg", "icon.svg.import", "project.godot"]

  # A list of glob expressions which, when any match are matched, cause an addon
  # file to be installed into a Godot project when it otherwise wouldn't be. This
  # option takes precedence over excluded files.
  include = []

[project.script_templates]
  # Include additional script templates from these directories into the project.
  # The directory structure within the folder pointed to by each pattern will be
  # merged into this project's 'script_templates' folder.
  include = []

  # Export non-imported script templates found in these directories.
  export = []

[dev-addons]
  Gut = {git = "https://github.com/bitwes/Gut.git", tag = "v9.2.1"}
