name: "🚀 Release: Plugin version"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: coffeebeats/godot-infra/.github/workflows/release-addon.yaml@v6
    secrets: inherit
    with:
      file-excludes: |
        **/AGENTS.md
        **/CLAUDE.md

        **/example
        **/examples
        **/*_test.gd
        **/*_test.gd.uid

  branch_protection:
    needs: [release]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Verify required jobs
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
